#!/bin/bash

# Copyright (C) 2015 Smartodds Ltd
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Global const vars

BASHRCD_DIR="${BASHRCD_DIR:-${HOME}/.bashrc.d}"

# Global vars

g_bashrcd_local_symbols=''


f_bashrcd_register_local_symbol() {
  g_bashrcd_local_symbols="${g_bashrcd_local_symbols} $1"
}
f_bashrcd_register_local_symbol f_bashrcd_register_local_symbol


f_bashrcd_abort() {
  local l_rc l_err

  l_rc="$1"
  l_err="$2"

  [[ -z "${l_err}" ]] || printf "%s" "${l_err}\n" >&2

  exit "${l_rc}"
}
f_bashrcd_register_local_symbol f_bashrcd_abort


f_bashrcd_init_userdir() {
  [[ -d "${BASHRCD_DIR}" ]] || mkdir -p "${BASHRCD_DIR}"
}
f_bashrcd_register_local_symbol f_bashrcd_init_userdir


f_bashrcd_process_scripts() {
  local \
    l_script \
    l_list

  l_list="$@"
  for l_script in ${l_list} ; do
    . "${l_script}"
  done
}
f_bashrcd_register_local_symbol f_bashrcd_process_scripts


f_bashrcd_check_run_parts() {
  local \
    l_cmd_busybox \
    l_cmd_run_parts

  l_cmd_run_parts="$(which run-parts 2>/dev/null)"
  if [[ "$?" -ne 0 ]]; then
    # Try with busybox
    l_cmd_busybox="$(which busybox 2>/dev/null)" || f_bashrcd_abort 2 "Unable to locate run-parts"
    ${l_cmd_busybox} --list | grep -q run-parts 2>/dev/null || f_bashrcd_abort 2 "Unable to locate run-parts"
    l_cmd_run_parts="${l_cmd_busybox} run-parts"
  fi

  [[ -n "${l_cmd_run_parts}" ]] || f_bashrcd_abort 2 "Unable to locate run-parts"
  printf "%s" "${l_cmd_run_parts}"
}
f_bashrcd_register_local_symbol f_bashrcd_check_run_parts


f_bashrcd_list_scripts() {
  local l_cmd_run_parts

  l_cmd_run_parts="$(f_bashrcd_check_run_parts)"
  ${l_cmd_run_parts} --list "${BASHRCD_DIR}"
}
f_bashrcd_register_local_symbol f_bashrcd_list_scripts


f_bashrcd_help() {
  cat >&2 <<EOF
Usage: $(basename $0) [-hn]
Execute scripts found in ${BASHRCD_DIR} in the current shell.

  Options:
   -h        Display this help and exit
   -n        List the scripts as they would be executed,
             without actually executing them.
EOF
}
f_bashrcd_register_local_symbol f_bashrcd_help


# main()

f_bashrcd_init_userdir

while getopts "hn" opt; do
  case "${opt}" in
    h)  f_bashrcd_help ; exit 0 ;;
    n)  f_bashrcd_list_scripts ; exit 0 ;;
    \?) f_bashrcd_help ; f_bashrcd_abort 1 ;;
  esac
done

shift "$((OPTIND-1))"

f_bashrcd_process_scripts $(f_bashrcd_list_scripts)


unset ${g_bashrcd_local_symbols}
unset g_bashrcd_local_symbols
